### PR TITLE
Feat: Add WhatsApp integration

### PR DESCRIPTION
**Pull request by sarsey-walker**
Added capability to send encrypted messages thought WhatsApp as like twitter.

It uses the phone numbers. Just put full number as handle.
Ex: 551199888888

### CODE REVIEW

**Comment by eddieoz** [comment]
I tried to run here and got an error:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'dataset')
    at findWhatsappNumber (content.js:50:75)`
    
 I'm using brave browser on Linux.

**Comment by sarsey-walker** [comment]
Thaks for the feedback. I'll check it tonight when I got from work.

**Comment by eddieoz** [comment]
@sarsey-walker I updated your version to be compatible with Twitter desktop/mobile and Whatsapp. The file contents.js.zip is attached (just unpack it to the /src folder)

Please check if it works in your environment, and then you can submit it.
[content.js.zip](https://github.com/eddieoz/openxrypt/files/15323894/content.js.zip)

**Comment by sarsey-walker** [comment]
@eddieoz I worked based on this file. Fixed some errors and is working fine on brave at windows. MAYBE that error from linux was gone. I'll check linux 'till morning bc i need some sleep

**Review by eddieoz — APPROVED** [review]
Tested both whatsapp and twitter.
Ready to ship.

**Pull request merged**
